/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.carrentalsystemalpha;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Daryl James
 */
public class CarADD extends javax.swing.JDialog {

    /**
     * Creates new form CarADD
     */
    public CarADD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Administrator - Add a Vehicle");
    }
    private JFrame frame;
    private File selectedFile;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel16 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        platenumfield = new javax.swing.JTextField();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        fuelcbox = new javax.swing.JComboBox<>();
        transcbox = new javax.swing.JComboBox<>();
        seatspnr = new javax.swing.JSpinner();
        jLabel114 = new javax.swing.JLabel();
        descfield = new javax.swing.JTextField();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        ratefield = new javax.swing.JFormattedTextField();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        ratefield2 = new javax.swing.JFormattedTextField();
        jLabel120 = new javax.swing.JLabel();
        jSeparator50 = new javax.swing.JSeparator();
        jSeparator51 = new javax.swing.JSeparator();
        jSeparator52 = new javax.swing.JSeparator();
        jSeparator53 = new javax.swing.JSeparator();
        jSeparator54 = new javax.swing.JSeparator();
        jSeparator55 = new javax.swing.JSeparator();
        jSeparator56 = new javax.swing.JSeparator();
        addingbtn = new javax.swing.JButton();
        previewbtn = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel121 = new javax.swing.JLabel();
        vhclbrndfield = new javax.swing.JTextField();
        vhclmdfield = new javax.swing.JTextField();
        vehicletypbx = new javax.swing.JComboBox<>();
        ratefield3 = new javax.swing.JFormattedTextField();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADD A VEHICLE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 14))); // NOI18N

        jLabel106.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel106.setText("Vehicle Information");

        jLabel107.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel107.setText("Vehicle Type :");

        jLabel108.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel108.setText("Vehicle Model :");

        jLabel109.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel109.setText("Vehicle Brand :");

        jLabel110.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel110.setText("Details");

        jLabel111.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel111.setText("Transmission :");

        jLabel112.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel112.setText("Seats :");

        jLabel113.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel113.setText("Description :");

        fuelcbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diesel", "Special", "Regular" }));
        fuelcbox.setSelectedIndex(-1);

        transcbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automatic", "Manual" }));
        transcbox.setSelectedIndex(-1);

        seatspnr.setModel(new javax.swing.SpinnerNumberModel(2, 2, 10, 1));
        seatspnr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel114.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel114.setText("Fuel Type :");

        jLabel115.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel115.setText("Rate");

        jLabel116.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel116.setText("12-hour Rate :");

        ratefield.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00#"))));
        ratefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratefieldActionPerformed(evt);
            }
        });

        jLabel117.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel117.setText("₱");

        jLabel118.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel118.setText("24-hour Rate :");

        jLabel119.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel119.setText("₱");

        ratefield2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00#"))));
        ratefield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratefield2jFormattedTextField3ActionPerformed(evt);
            }
        });

        jLabel120.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel120.setText("Image");

        addingbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        addingbtn.setText("Add Image");
        addingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addingbtnActionPerformed(evt);
            }
        });

        previewbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        previewbtn.setText("Preview");
        previewbtn.setToolTipText("");
        previewbtn.setEnabled(false);
        previewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewbtnActionPerformed(evt);
            }
        });

        jButton23.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jButton23.setText("Save");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23jButton3ActionPerformed(evt);
            }
        });

        clearbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnjButton4ActionPerformed(evt);
            }
        });

        jButton24.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jButton24.setText("Cancel");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24jButton5ActionPerformed(evt);
            }
        });

        jLabel121.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel121.setText("Plate No :");

        vhclbrndfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vhclbrndfieldActionPerformed(evt);
            }
        });

        vehicletypbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Motor", "Pick Up", "Sedan", "SUV", "Other..." }));
        vehicletypbx.setSelectedIndex(-1);
        vehicletypbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicletypbxActionPerformed(evt);
            }
        });

        ratefield3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00#"))));
        ratefield3.setText("200.00");
        ratefield3.setEnabled(false);
        ratefield3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        ratefield3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratefield3jFormattedTextField3ActionPerformed(evt);
            }
        });

        jLabel122.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel122.setText("₱");

        jLabel123.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel123.setText("Excess Rate :");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator55)
                    .addComponent(jSeparator50)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel107)
                            .addComponent(jLabel106)
                            .addComponent(jLabel108)
                            .addComponent(jLabel109)
                            .addComponent(jLabel121))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(platenumfield)
                            .addComponent(vhclbrndfield)
                            .addComponent(vhclmdfield)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(vehicletypbx, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel116)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel117)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ratefield, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel118)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addComponent(jLabel119)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ratefield2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel114)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fuelcbox, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel111)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(transcbox, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel112)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(seatspnr, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator56)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel120)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addingbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(previewbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator51)
                    .addComponent(jSeparator52)
                    .addComponent(jSeparator53)
                    .addComponent(jSeparator54)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel123)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                        .addComponent(jLabel122)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ratefield3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel110)
                            .addComponent(jLabel115))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel113)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descfield, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel106)
                .addGap(4, 4, 4)
                .addComponent(jSeparator50, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel107)
                    .addComponent(vehicletypbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel108)
                    .addComponent(vhclmdfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel109)
                    .addComponent(vhclbrndfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel121)
                    .addComponent(platenumfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator51, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel110)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator52, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel114)
                    .addComponent(fuelcbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel111)
                    .addComponent(transcbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel112)
                    .addComponent(seatspnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel113)
                    .addComponent(descfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator53, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel115)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator54, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel116)
                    .addComponent(ratefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel117))
                .addGap(2, 2, 2)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel118)
                    .addComponent(ratefield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel119))
                .addGap(2, 2, 2)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel123)
                    .addComponent(ratefield3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel122))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator55, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addingbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel120)
                    .addComponent(previewbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator56, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void ratefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ratefieldActionPerformed

    private void ratefield2jFormattedTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratefield2jFormattedTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ratefield2jFormattedTextField3ActionPerformed

    @SuppressWarnings("empty-statement")
    private void jButton23jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23jButton3ActionPerformed
       
            
        //Vehicle Information

        String car_type = (String) vehicletypbx.getSelectedItem();      

       
        String model = vhclmdfield.getText().trim();
        String brand = vhclbrndfield.getText().trim();
        String plate = platenumfield.getText().trim();    
         
        //Car Details
        String fuel = (String) fuelcbox.getSelectedItem();
        String transmission = (String) transcbox.getSelectedItem();
        int capacity = (Integer) seatspnr.getValue();
        String description = descfield.getText().trim();

        double rate12 = 0.0;
        double rate24 = 0.0;

       
  
        if (vehicletypbx.getSelectedItem() == null) {
         Error error = new Error(this,true,"Please fill out the fields.");
         error.setVisible(true);
        }
        
        
        else if ( model.isEmpty() ||
            brand.isEmpty() || plate.isEmpty() ||
            fuel.isEmpty()  || transmission.isEmpty()||
            description.isEmpty()) {
            Error error = new Error(this, true, "Please fill up the fields.");
            error.setVisible(true);
       }
       
        else if (ratefield.getValue() == null) {
            Error error = new Error(this,true,"12-hour rate cannot be empty");
            error.setVisible(true);
        } else if (ratefield2.getValue() == null){
            Error error = new Error(this,true,"24-hour rate cannot be empty");
            error.setVisible(true);
        }           
        else if (capacity == 0) {
             Error error = new Error(this, true, "Please enter a seat");
            error.setVisible(true);
        }
        
         else if (capacity == 0) {
             Error error = new Error(this, true, "Please enter a seat");
            error.setVisible(true);
        }
        
         else if (((Number) ratefield.getValue()).doubleValue() <= 0 || ((Number) ratefield2.getValue()).doubleValue() <= 0) {
             Error error = new Error(this, true, "Please enter a valid rate.");
            error.setVisible(true);
        }
            
         else if (selectedFile == null) {
             Error error = new Error(this, true, "Please add an image for your vehicle.");
            error.setVisible(true);
         }
         
         else if (vehicletypbx.getSelectedIndex() == 0 && fuelcbox.getSelectedIndex() == 0) {
              Error error = new Error(this, true, "A Motorcycle cannot have Diesel as fuel");
            error.setVisible(true);
        }
         
         else{
            rate12 = ((Number) ratefield.getValue()).doubleValue();
            rate24 = ((Number) ratefield2.getValue()).doubleValue();

            if (rate12 >= rate24) {
              Error error = new Error(this, true, "12-hour rate must not be higher than 24-hour");
              error.setVisible(true);
              return;
            }
            
            
          try (Connection conn = DatabaseConnection.connect()) {
        String sql = "INSERT INTO car_table (vehicle_type, vehicle_model, vehicle_brand,plate_num, fuel_type, transmission, seats, description, rate_12, rate_24, carimg_path, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);

        
        pst.setString(1, car_type);
        pst.setString(2, model);
        pst.setString(3, brand);
        pst.setString(4, plate);
        pst.setString(5, fuel);
        pst.setString(6, transmission);
        pst.setInt(7, capacity);
        pst.setString(8, description);
        pst.setDouble(9, rate12);
        pst.setDouble(10, rate24);
        pst.setString(11, selectedFile.getAbsolutePath());
        pst.setString(12, "Available");
        
        

        int rows = pst.executeUpdate();
        if (rows > 0) {
            Success dialog1 = new Success(this,true,"A new vehicle has been added!");
            dialog1.setVisible(true);
                
    // Close the registration form
    this.dispose();
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }  } 
    }//GEN-LAST:event_jButton23jButton3ActionPerformed

    private void clearbtnjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnjButton4ActionPerformed
        
        
        //textfields
        vhclmdfield.setText("");
        vhclbrndfield.setText("");
        platenumfield.setText("");
        descfield.setText("");
        
        // comboboxes
        vehicletypbx.setSelectedIndex(-1);  
        fuelcbox.setSelectedIndex(-1);  
        transcbox.setSelectedIndex(-1);  
        
        //spinner
        seatspnr.setValue(2);
        
        // formatted fields
        ratefield.setText("");
        ratefield2.setText("");	
        
        //file
        selectedFile = null; 
        if (selectedFile == null) {
          previewbtn.setEnabled(false);  
        }// TODO add your handling code here:
    }//GEN-LAST:event_clearbtnjButton4ActionPerformed

    private void jButton24jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24jButton5ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24jButton5ActionPerformed

    private void vhclbrndfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vhclbrndfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vhclbrndfieldActionPerformed

    private void addingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addingbtnActionPerformed
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileFilter(new FileNameExtensionFilter(
                "Image Files (*.jpg, *.png)", "jpg", "jpeg", "png"));
            fileChooser.setAcceptAllFileFilterUsed(false);

            int option = fileChooser.showOpenDialog(frame);
            if (option == JFileChooser.APPROVE_OPTION) {
                selectedFile = fileChooser.getSelectedFile();
                previewbtn.setEnabled(true);
            }                        // TODO add your handling code here:
    }//GEN-LAST:event_addingbtnActionPerformed

    private void previewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewbtnActionPerformed
         if (selectedFile != null) {
                // Show image in a dialog
                ImageIcon icon = new ImageIcon(
                    new ImageIcon(selectedFile.getAbsolutePath())
                        .getImage()
                        .getScaledInstance(400, 300, Image.SCALE_SMOOTH)
                );

                JLabel imgLabel = new JLabel(icon);
                JOptionPane.showMessageDialog(frame, imgLabel, 
                        "Preview Image", JOptionPane.PLAIN_MESSAGE);
               
            }        // TODO add your handling code here:
    }//GEN-LAST:event_previewbtnActionPerformed

    private void vehicletypbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicletypbxActionPerformed
        if (vehicletypbx.getSelectedIndex() == 0) {
            seatspnr.setEnabled(false);
            seatspnr.setValue(2); // TODO add your handling code here:
        }
        else {
             seatspnr.setEnabled(true);       
                    }
    }//GEN-LAST:event_vehicletypbxActionPerformed

    private void ratefield3jFormattedTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratefield3jFormattedTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ratefield3jFormattedTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {
            // Apply modern Look and Feel for all Swing components
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //</editor-fold>
            
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CarADD dialog = new CarADD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addingbtn;
    private javax.swing.JButton clearbtn;
    private javax.swing.JTextField descfield;
    private javax.swing.JComboBox<String> fuelcbox;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JSeparator jSeparator50;
    private javax.swing.JSeparator jSeparator51;
    private javax.swing.JSeparator jSeparator52;
    private javax.swing.JSeparator jSeparator53;
    private javax.swing.JSeparator jSeparator54;
    private javax.swing.JSeparator jSeparator55;
    private javax.swing.JSeparator jSeparator56;
    private javax.swing.JTextField platenumfield;
    private javax.swing.JButton previewbtn;
    private javax.swing.JFormattedTextField ratefield;
    private javax.swing.JFormattedTextField ratefield2;
    private javax.swing.JFormattedTextField ratefield3;
    private javax.swing.JSpinner seatspnr;
    private javax.swing.JComboBox<String> transcbox;
    private javax.swing.JComboBox<String> vehicletypbx;
    private javax.swing.JTextField vhclbrndfield;
    private javax.swing.JTextField vhclmdfield;
    // End of variables declaration//GEN-END:variables
}
