/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.carrentalsystemalpha;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daryl James
 */
public class CarDialog extends javax.swing.JDialog {
private JFrame frame;
private String carimgpath;    
private String selectedID = null;
    /**
     * Creates new form CarDialog
     */
    public CarDialog(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Car Rental System - Select Vehicle");
        setLocationRelativeTo(null);
        cardata();
        carselector();
    }
    
    
    
    private void cardata() {
        cartable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        try (Connection conn = DatabaseConnection.connect()) {

         DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Vehicle ID", "Vehicle Brand", "Vehicle Model", "Plate No"});

        String sql = "SELECT vehicle_id, vehicle_brand, vehicle_model, plate_num FROM car_table WHERE status = 'Available'";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(sql);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("vehicle_id"),
                rs.getString("vehicle_brand"),
                rs.getString("vehicle_model"),
                rs.getString("plate_num"),
            });
        }

        cartable.setModel(model); 
        cartable.setDefaultEditor(Object.class, null);
             
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }
    
      private void carselector() {
       cartable.getSelectionModel().addListSelectionListener(e -> {
    if (!e.getValueIsAdjusting() && cartable.getSelectedRow() != -1) {
        int selectedRow = cartable.getSelectedRow();
        
        CardLayout cl = (CardLayout) cardL.getLayout();
        cardL.add(NoCar, "TIP");        // default tip
        cardL.add(SelectedCar, "DETAILS");
        cl.show(cardL, "DETAILS"); 
           
        String carId = cartable.getValueAt(selectedRow, 0).toString(); 
        loadCarDetailsFromDatabase(carId); 
        selectbtn.setEnabled(true);
    }
    });
   }    
    
    
   public void loadCarDetailsFromDatabase(String carId) {
    Connection conn = DatabaseConnection.connect();
    String sql = "SELECT * FROM car_table WHERE vehicle_id = ?";
    try (PreparedStatement pst = conn.prepareStatement(sql)) {
        pst.setString(1, carId);
        try (ResultSet rs = pst.executeQuery()) {
            if (rs.next()) {
                vehicleIdlbl.setText(rs.getString("vehicle_id"));
                vehicltypelbl.setText(rs.getString("vehicle_type"));
                fuellbl.setText(rs.getString("fuel_type"));
                translbl.setText(rs.getString("transmission"));
                seatlbl.setText(rs.getString("seats"));
                hr12lbl.setText(rs.getString("rate_12"));
                hr24lbl.setText(rs.getString("rate_24"));
                description.setText(rs.getString("description"));
                carimgpath = rs.getString("carimg_path");

                
                 if (carimgpath != null && !carimgpath.isEmpty()) {
                    viewimgbtn.setEnabled(true);   
                } else {
                    viewimgbtn.setEnabled(false);
                }
                
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
}
  
     public String getSelectedID() {
        return selectedID;
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cardL = new javax.swing.JPanel();
        NoCar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        SelectedCar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        vehicleIdlbl = new javax.swing.JLabel();
        fuellbl = new javax.swing.JLabel();
        translbl = new javax.swing.JLabel();
        seatlbl = new javax.swing.JLabel();
        hr12lbl = new javax.swing.JLabel();
        hr24lbl = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        selectbtn = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        viewimgbtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jlabelsmth = new javax.swing.JLabel();
        vehicltypelbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SELECT AN AVAILABLE VEHICLE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 14))); // NOI18N

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        cartable.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        cartable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Vehicle ID", "Vehicle Brand", "Vehicle Type", "Plate No."
            }
        ));
        cartable.setRowHeight(26);
        cartable.setShowHorizontalLines(false);
        cartable.setShowVerticalLines(false);
        cartable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(cartable);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.png"))); // NOI18N

        jLabel2.setText("Please select a vehicle that listed as available");

        jLabel3.setText("from the table.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(jLabel3)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        cardL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VEHICLE INFORMATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 13))); // NOI18N
        cardL.setLayout(new java.awt.CardLayout());

        jLabel8.setText("No Vehicle Selected.");

        javax.swing.GroupLayout NoCarLayout = new javax.swing.GroupLayout(NoCar);
        NoCar.setLayout(NoCarLayout);
        NoCarLayout.setHorizontalGroup(
            NoCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoCarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel8)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        NoCarLayout.setVerticalGroup(
            NoCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoCarLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel8)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        cardL.add(NoCar, "card3");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel9.setText("Vehicle ID :");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel10.setText("Fuel Type");

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel11.setText("Transmission:");

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel12.setText("Seats :");

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel13.setText("12-Hour Rate :");

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel14.setText("24-Hour Rate :");

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel15.setText("Excess Rate:");

        vehicleIdlbl.setText("null");

        fuellbl.setText("null");

        translbl.setText("null");

        seatlbl.setText("null");

        hr12lbl.setText("null");

        hr24lbl.setText("null");

        jLabel22.setText("200");

        selectbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        selectbtn.setText("Select");
        selectbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectbtnActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButton5.setText("Cancel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        viewimgbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        viewimgbtn.setText("View Vehicle Image");
        viewimgbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewimgbtnActionPerformed(evt);
            }
        });

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        description.setEditable(false);
        description.setBackground(new java.awt.Color(240, 240, 240));
        description.setColumns(20);
        description.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        description.setLineWrap(true);
        description.setRows(5);
        description.setText("null\n");
        description.setWrapStyleWord(true);
        jScrollPane3.setViewportView(description);

        jLabel23.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel23.setText("Description :");

        jlabelsmth.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jlabelsmth.setText("Vehicle Type :");

        vehicltypelbl.setText("null");

        javax.swing.GroupLayout SelectedCarLayout = new javax.swing.GroupLayout(SelectedCar);
        SelectedCar.setLayout(SelectedCarLayout);
        SelectedCarLayout.setHorizontalGroup(
            SelectedCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectedCarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SelectedCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewimgbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(selectbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SelectedCarLayout.createSequentialGroup()
                        .addGroup(SelectedCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SelectedCarLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22))
                            .addGroup(SelectedCarLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vehicleIdlbl))
                            .addGroup(SelectedCarLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fuellbl))
                            .addGroup(SelectedCarLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(translbl))
                            .addGroup(SelectedCarLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatlbl))
                            .addGroup(SelectedCarLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hr12lbl))
                            .addGroup(SelectedCarLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hr24lbl))
                            .addComponent(jLabel23)
                            .addGroup(SelectedCarLayout.createSequentialGroup()
                                .addComponent(jlabelsmth)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vehicltypelbl)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        SelectedCarLayout.setVerticalGroup(
            SelectedCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectedCarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(SelectedCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(vehicleIdlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SelectedCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelsmth)
                    .addComponent(vehicltypelbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SelectedCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fuellbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SelectedCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(translbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SelectedCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(seatlbl))
                .addGap(8, 8, 8)
                .addGroup(SelectedCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(hr12lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SelectedCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(hr24lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SelectedCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(viewimgbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap())
        );

        cardL.add(SelectedCar, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cardL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewimgbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewimgbtnActionPerformed
    
     File imgFile = new File(carimgpath);
    ImageIcon icon = new ImageIcon(
        new ImageIcon(imgFile.getAbsolutePath())
            .getImage()
            .getScaledInstance(400, 300, Image.SCALE_SMOOTH)
    );

    JLabel imgLabel = new JLabel(icon);
    JOptionPane.showMessageDialog(frame, imgLabel, 
            "Preview Image", JOptionPane.PLAIN_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_viewimgbtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void selectbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectbtnActionPerformed
        selectedID = vehicleIdlbl.getText();
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_selectbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {
            // Apply modern Look and Feel for all Swing components
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the dialog */
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NoCar;
    private javax.swing.JPanel SelectedCar;
    private javax.swing.JPanel cardL;
    private javax.swing.JTable cartable;
    private javax.swing.JTextArea description;
    private javax.swing.JLabel fuellbl;
    private javax.swing.JLabel hr12lbl;
    private javax.swing.JLabel hr24lbl;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlabelsmth;
    private javax.swing.JLabel seatlbl;
    private javax.swing.JButton selectbtn;
    private javax.swing.JLabel translbl;
    private javax.swing.JLabel vehicleIdlbl;
    private javax.swing.JLabel vehicltypelbl;
    private javax.swing.JButton viewimgbtn;
    // End of variables declaration//GEN-END:variables
}
