/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.carrentalsystemalpha;

import com.formdev.flatlaf.FlatLightLaf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Daryl James
 */
public class Login1 extends javax.swing.JFrame {

    /**
     * Creates new form Login1
     */
    public Login1() {
        initComponents();
        setTitle("Car Rental System - Login");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UserF = new javax.swing.JTextField();
        PassF = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        PassChcbx = new javax.swing.JCheckBox();
        LogBttn = new javax.swing.JButton();
        forgetpasslbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1carback.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-350, 0, 670, 480));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo2.png"))); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel3.setText("LOGIN");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("Username");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setText("Password");

        PassChcbx.setText("Show Password");
        PassChcbx.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PassChcbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassChcbxActionPerformed(evt);
            }
        });

        LogBttn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        LogBttn.setText("Login");
        LogBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogBttnActionPerformed(evt);
            }
        });

        forgetpasslbl.setForeground(new java.awt.Color(0, 51, 255));
        forgetpasslbl.setText("<html><u>Forget Password?</u></html>");
        forgetpasslbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgetpasslbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetpasslblMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel7.setText("v1.1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(80, 80, 80)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PassF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(UserF, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(PassChcbx, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LogBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(forgetpasslbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PassF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PassChcbx)
                .addGap(33, 33, 33)
                .addComponent(LogBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(forgetpasslbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel7))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 240, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forgetpasslblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetpasslblMouseClicked
    forgetpass dialog = new forgetpass(this,true);
    dialog.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_forgetpasslblMouseClicked

    private void LogBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogBttnActionPerformed
      
  String username = UserF.getText();
  String password = new String(PassF.getPassword());

if (username.isEmpty() || password.isEmpty()) {
    Error dialog = new Error(this, true, "Please Fill out the Fields.");
    dialog.setVisible(true);
    LogBttn.setEnabled(true);
    return; // stop here if empty
}   

String hashedPassword = Integer.toHexString(password.hashCode());
int userId = -1;

try {
    LogBttn.setEnabled(false);
    Connection conn = DatabaseConnection.connect();
   String sql = "SELECT u.user_id, u.password, u.role, m.reset_confirmed, m.is_banned, m.ban_reason " +
             "FROM user_table u " +
             "JOIN user_data m ON u.user_id = m.user_id " +
             "WHERE u.full_name = ?";

    PreparedStatement pst = conn.prepareStatement(sql);
    pst.setString(1, username);
    ResultSet rs = pst.executeQuery();

    if (rs.next()) {
        userId = rs.getInt("user_id");
        String role = rs.getString("role");
        Boolean isban = rs.getBoolean("is_banned");
        String ban_reason = rs.getString("ban_reason");
        String dbPassword = rs.getString("password");
        boolean passreset = rs.getBoolean("reset_confirmed");

        if(passreset) {
                 final int uid = userId;
                java.awt.EventQueue.invokeLater(() -> {
                   ConfirmedPass confirmedPassDialog = new ConfirmedPass(this, true, uid);
                    confirmedPassDialog.setVisible(true);
                    LogBttn.setEnabled(true);

                     if(confirmedPassDialog.isPasswordChanged()) {  // you can create a boolean property in ConfirmedPass
                        this.dispose();
                         new AdminA(uid).setVisible(true);
                      } 
                });     
        }
        
        else if (isban) {
            JOptionPane.showMessageDialog(null,"Your Account is banned.\nReason:" + ban_reason + 
                    "\n\n" + "If you believe this is a mistake, please contact the Administrator.","Access Denied"
                    ,JOptionPane.WARNING_MESSAGE);    
            LogBttn.setEnabled(true);
            return;
        }  
        
        
        else if (dbPassword.equals(hashedPassword)) { 
            if ("Admin".equalsIgnoreCase(role)||"S_Admin".equalsIgnoreCase(role)) {
            final int uid = userId;
            java.awt.EventQueue.invokeLater(() -> {
                new AdminA(uid).setVisible(true);
                this.dispose();
            });
            }
             else {
          
           JOptionPane.showMessageDialog(null, """
                                               Clients are no longer allowed to login after update v0.7c 
                                                Reason :
                                               The system has been converted from Management System.""","Access Denied"
            ,JOptionPane.WARNING_MESSAGE);    
           LogBttn.setEnabled(true);
            return;
        }
            
        }          
         else  { 
           Error error = new Error(this,true, "Wrong Username or Password");
           LogBttn.setEnabled(true);
           error.setVisible(true);     
           

        }
    } else {
        Error dialog = new Error(this, true, "User not Found.");
        dialog.setVisible(true);
        LogBttn.setEnabled(true);
    }

    rs.close();
    pst.close();
    conn.close();

    } catch (Exception e) {
        e.printStackTrace();
       
        Error dialog = new Error(this, true, "Error: " + e.getMessage());
        LogBttn.setEnabled(true);
        dialog.setVisible(true);
    }     // TODO add your handling code here:
    }//GEN-LAST:event_LogBttnActionPerformed

    private void PassChcbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassChcbxActionPerformed
      if (PassChcbx.isSelected()) {
        PassF.setEchoChar((char) 0);
        PassChcbx.setText("Hide Password");
    } else {
        PassF.setEchoChar('•');
        PassChcbx.setText("Show Password");
    }         // TODO add your handling code here:
    }//GEN-LAST:event_PassChcbxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {
            // Apply modern Look and Feel for all Swing components
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogBttn;
    private javax.swing.JCheckBox PassChcbx;
    private javax.swing.JPasswordField PassF;
    private javax.swing.JTextField UserF;
    private javax.swing.JLabel forgetpasslbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
