/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.carrentalsystemalpha;

import com.formdev.flatlaf.FlatLightLaf;
import java.sql.*;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDateTime;
import javax.swing.UIManager;

/**
 *
 * @author Daryl James
 */
public class Receipt extends javax.swing.JDialog {

    /**
     * Creates new form Receipt
     */
    
    private final int payID;
    
    public Receipt(java.awt.Frame parent, boolean modal, int payId) {
        super(parent, modal);
        initComponents();
        this.payID = payId;
        setLocationRelativeTo(null);
        setTitle("Car Rental System - Receipt");
        getdata();
    }

    private void getdata() {
        String sql = "SELECT " +
    "p.payment_id, " +
    "p.total_cost, " +
    "p.fully_paid_date, " +
    "p.deposit_amt, " +
    "p.reservation_fee, " +
    "r.reservation_id, " +
    "r.start_date, " +
    "r.end_date, " +
    "v.vehicle_model AS vehicle_model, " +
    "u.full_name AS client_name, " +
    "u2.full_name AS made_by_admin " +
    "FROM payment_tbl p " +
    "JOIN reservations_table r ON p.reservation_id = r.reservation_id " +
    "JOIN car_table v ON r.car_id = v.vehicle_id " +
    "JOIN user_table u ON r.user_id = u.user_id " +
    "JOIN user_table u2 ON r.made_by = u2.user_id " +
    "WHERE p.payment_id = ?";
        
        int hourlyRate = 200;
        try (Connection conn = DatabaseConnection.connect()) {
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, payID);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                payidlbl.setText(rs.getString("payment_id"));
                Timestamp ts = rs.getTimestamp("fully_paid_date");
           
                if (ts != null) {
                    String formattedDate = new SimpleDateFormat("MM/dd/yyyy - HH:mm").format(ts);
                    datelbl.setText(formattedDate);
                }
                    issuelbl.setText(rs.getString("made_by_admin"));
                    reservlbl.setText(rs.getString("reservation_id"));
                    clnmlbl.setText(rs.getString("client_name"));
                    carlbl.setText(rs.getString("vehicle_model"));
                    Timestamp start = rs.getTimestamp("start_date");
                    Timestamp end = rs.getTimestamp("end_date");
                if (start != null && end != null) {
                    String formattedDate = new SimpleDateFormat("MM/dd/yyyy - HH:mm").format(start);
                    String formattedDate1 = new SimpleDateFormat("MM/dd/yyyy - HH:mm").format(end);
                    startlbl.setText(formattedDate);
                    endlbl.setText(formattedDate1);
                }    
                    LocalDateTime startDateTime = start.toLocalDateTime();
                    LocalDateTime endDateTime = end.toLocalDateTime();
                    
                    Duration durations = Duration.between(startDateTime, endDateTime);
                    long totalHours = durations.toHours();
                    long days = totalHours / 24;
                    long hours = totalHours % 24;
                    if (days == 0) {
                    durtnlbl.setText(hours + " Hours");
                    } else {
                            durtnlbl.setText(days + " day(s) " + hours + " hour(s)");
                    }    
                    DecimalFormat df = new DecimalFormat("#,##0.00"); 
                    int deposit = rs.getInt("deposit_amt");
                    int resrvfee = rs.getInt("reservation_fee");
                    
                    depositlbl.setText(String.valueOf(df.format(deposit)));
                    reservfeelbl.setText(String.valueOf(df.format(resrvfee)));
               if (hours > 0 && hours <= 6) {
                    exceslbl.setText(df.format(hours * hourlyRate));
                } else {
                    exceslbl.setText(df.format(0.00));
                }
                    int total = rs.getInt("total_cost");
                    int rentalcost = total - (deposit + resrvfee);
                    rentalcstlbl.setText(df.format(rentalcost));
                    
                    totallbl.setText(df.format(total));          
            }
            
        }
        catch (SQLException e) {
            e.printStackTrace();
        }
    
    
    
    
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        payidlbl = new javax.swing.JLabel();
        datelbl = new javax.swing.JLabel();
        reservlbl = new javax.swing.JLabel();
        clnmlbl = new javax.swing.JLabel();
        carlbl = new javax.swing.JLabel();
        durtnlbl = new javax.swing.JLabel();
        rentalcstlbl = new javax.swing.JLabel();
        totallbl = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        issuelbl = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        rentalcstlbl1 = new javax.swing.JLabel();
        rentalcstlbl2 = new javax.swing.JLabel();
        depositlbl = new javax.swing.JLabel();
        rentalcstlbl4 = new javax.swing.JLabel();
        reservfeelbl = new javax.swing.JLabel();
        rentalcstlbl6 = new javax.swing.JLabel();
        exceslbl = new javax.swing.JLabel();
        rentalcstlbl8 = new javax.swing.JLabel();
        startlbl = new javax.swing.JLabel();
        endlbl = new javax.swing.JLabel();
        startlbl1 = new javax.swing.JLabel();
        startlbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo2.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel2.setText(" ========== RENTAL RECEIPT  ==========");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setText("Payment No. :");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setText("Date Issued :");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel5.setText("Reservation No. :");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("P-2 Brgy.24 A Paz Village Gingoog City");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("+639639445288");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ace41al@gmail.com");

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel9.setText("Client Name :");

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel10.setText("Reservation Date :");

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel11.setText("Duration :");

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel12.setText("Car Model :");

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel13.setText("Rental Cost :");

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel14.setText("Deposit Cost :");

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel15.setText("Reservation Fee :");

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel16.setText("Excess Rate :");

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel17.setText("Total Cost ");

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel18.setText(" =================================");

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel19.setText("Thank you for choosing our Car Rental!");

        payidlbl.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        payidlbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        payidlbl.setText("null");

        datelbl.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        datelbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        datelbl.setText("null");

        reservlbl.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        reservlbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        reservlbl.setText("null");

        clnmlbl.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        clnmlbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clnmlbl.setText("null");

        carlbl.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        carlbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        carlbl.setText("null");

        durtnlbl.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        durtnlbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        durtnlbl.setText("null");

        rentalcstlbl.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rentalcstlbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rentalcstlbl.setText("null");

        totallbl.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        totallbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totallbl.setText("null");

        jLabel32.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel32.setText("Issued By :");

        issuelbl.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        issuelbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        issuelbl.setText("null");

        jLabel34.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("PYN-");

        jLabel35.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("RSVN-");

        rentalcstlbl1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rentalcstlbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rentalcstlbl1.setText("₱");

        rentalcstlbl2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rentalcstlbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rentalcstlbl2.setText("₱");

        depositlbl.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        depositlbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        depositlbl.setText("null");

        rentalcstlbl4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rentalcstlbl4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rentalcstlbl4.setText("₱");

        reservfeelbl.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        reservfeelbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        reservfeelbl.setText("null");

        rentalcstlbl6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rentalcstlbl6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rentalcstlbl6.setText("₱");

        exceslbl.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        exceslbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        exceslbl.setText("0.00");

        rentalcstlbl8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        rentalcstlbl8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rentalcstlbl8.setText("₱");

        startlbl.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        startlbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        startlbl.setText("null");

        endlbl.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        endlbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        endlbl.setText("null");

        startlbl1.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        startlbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        startlbl1.setText("End Date :");

        startlbl2.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        startlbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        startlbl2.setText("Start Date:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(issuelbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(rentalcstlbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0)
                                .addComponent(depositlbl))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(rentalcstlbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0)
                                .addComponent(reservfeelbl))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(rentalcstlbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0)
                                .addComponent(exceslbl))
                            .addComponent(datelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0)
                                .addComponent(payidlbl))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(rentalcstlbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0)
                                .addComponent(rentalcstlbl))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0)
                                .addComponent(reservlbl))
                            .addComponent(durtnlbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(carlbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clnmlbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(rentalcstlbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(totallbl))
                            .addComponent(endlbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel32)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(startlbl2)
                                        .addGap(0, 0, 0)
                                        .addComponent(startlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(startlbl1))))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel19)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(77, 77, 77))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(payidlbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(datelbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(issuelbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(reservlbl)
                                    .addComponent(jLabel35))
                                .addGap(25, 25, 25)
                                .addComponent(clnmlbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carlbl))
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startlbl)
                            .addComponent(startlbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(endlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startlbl1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(durtnlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rentalcstlbl)
                            .addComponent(rentalcstlbl1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(depositlbl)
                            .addComponent(rentalcstlbl2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reservfeelbl)
                            .addComponent(rentalcstlbl4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exceslbl)
                            .addComponent(rentalcstlbl6))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totallbl)
                            .addComponent(rentalcstlbl8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
                      try {
            // Apply modern Look and Feel for all Swing components
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Receipt dialog = new Receipt(new javax.swing.JFrame(), true,31);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        /* Create and display the dialog */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carlbl;
    private javax.swing.JLabel clnmlbl;
    private javax.swing.JLabel datelbl;
    private javax.swing.JLabel depositlbl;
    private javax.swing.JLabel durtnlbl;
    private javax.swing.JLabel endlbl;
    private javax.swing.JLabel exceslbl;
    private javax.swing.JLabel issuelbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel payidlbl;
    private javax.swing.JLabel rentalcstlbl;
    private javax.swing.JLabel rentalcstlbl1;
    private javax.swing.JLabel rentalcstlbl2;
    private javax.swing.JLabel rentalcstlbl4;
    private javax.swing.JLabel rentalcstlbl6;
    private javax.swing.JLabel rentalcstlbl8;
    private javax.swing.JLabel reservfeelbl;
    private javax.swing.JLabel reservlbl;
    private javax.swing.JLabel startlbl;
    private javax.swing.JLabel startlbl1;
    private javax.swing.JLabel startlbl2;
    private javax.swing.JLabel totallbl;
    // End of variables declaration//GEN-END:variables
}
